# Dropbear Android Gitlab Builder
# http://doc.gitlab.com/ce/ci/yaml/README.html
# https://hub.docker.com/_/debian/

image: debian:latest

variables:
  TERM: xterm
  BIN: bin
  INTERACTIVE: 0
 
before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget xz-utils autoconf make binutils build-essential git
stages:
  - build

pages:
  stage: build
  only:
    - master
  script:
    - ./build.sh
    - export DATE=$(date -u +"%m%d%H%M%S")
    - mkdir -p "${BIN}"
    - mv -v target/arm/* "${BIN}/"
  artifacts:
    name: dropbear-android-${DATE}
    paths:
      - ${BIN}
